
[E 120725 15:00:02 app:118] NotFound
[E 120725 15:00:02 web:1064] Uncaught exception GET /genreid/7654 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/7654', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 119, in get
        logging.error(mgs["StatusMsg"])
    KeyError: 'StatusMsg'
[E 120725 15:00:02 web:1447] 500 GET /genreid/7654 (192.168.32.17) 68.21ms
[W 120725 15:00:03 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120725 15:00:50 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120725 15:00:52 app:118] NotFound
[E 120725 15:00:52 web:1064] Uncaught exception GET /genreid/7654 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/7654', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 119, in get
        logging.error(mgs["StatusMsg"])
    KeyError: 'StatusMsg'
[E 120725 15:00:52 web:1447] 500 GET /genreid/7654 (192.168.32.17) 28.30ms
[W 120725 15:00:53 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[E 120725 15:00:54 app:118] NotFound
[E 120725 15:00:54 web:1064] Uncaught exception GET /genreid/7654 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/7654', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 119, in get
        logging.error(mgs["StatusMsg"])
    KeyError: 'StatusMsg'
[E 120725 15:00:54 web:1447] 500 GET /genreid/7654 (192.168.32.17) 56.10ms
[W 120725 15:00:55 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.52ms
[I 120725 15:01:03 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120725 15:01:04 app:118] NotFound
[W 120725 15:01:04 web:1447] 404 GET /genreid/7654 (192.168.32.17) 44.25ms
[W 120725 15:01:04 web:1447] 404 GET /favicon.ico (192.168.32.17) 1.10ms
[E 120725 15:01:24 app:118] NotFound
[W 120725 15:01:24 web:1447] 404 GET /genreid/7654 (192.168.32.17) 27.58ms
[W 120725 15:01:25 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120725 15:01:27 app:118] NotFound
[W 120725 15:01:27 web:1447] 404 GET /genreid/7654 (192.168.32.17) 17.75ms
[W 120725 15:01:27 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[E 120725 15:01:27 app:118] NotFound
[W 120725 15:01:27 web:1447] 404 GET /genreid/7654 (192.168.32.17) 32.57ms
[W 120725 15:01:27 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120725 15:01:27 app:118] NotFound
[W 120725 15:01:27 web:1447] 404 GET /genreid/7654 (192.168.32.17) 24.40ms
[W 120725 15:01:28 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[I 120725 15:02:28 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120725 15:02:53 app:118] Status : NotFound
[W 120725 15:02:53 web:1447] 404 GET /genreid/7654 (192.168.32.17) 35.47ms
[W 120725 15:02:54 web:1447] 404 GET /favicon.ico (192.168.32.17) 1.17ms
[E 120725 15:02:59 app:118] Status : NotFound
[W 120725 15:02:59 web:1447] 404 GET /genreid/7654 (192.168.32.17) 30.99ms
[W 120725 15:02:59 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.86ms
[I 120725 15:03:45 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120725 15:04:10 app:118] Bad message (TypeError('not enough arguments for format string',)): {'threadName': 'MainThread', 'name': 'root', 'thread': 140293953246976, 'created': 1343196250.3347011, 'process': 30922, 'processName': 'MainProcess', 'args': ((u'NotFound', u'7654'),), 'module': 'app', 'filename': 'app.py', 'levelno': 40, 'exc_text': None, 'pathname': '/root/bipapa/app.py', 'lineno': 118, 'asctime': '120725 15:04:10', 'msg': 'genreid %s is %s', 'exc_info': None, 'message': "Bad message (TypeError('not enough arguments for format string',)): {'threadName': 'MainThread', 'name': 'root', 'thread': 140293953246976, 'created': 1343196250.3347011, 'process': 30922, 'processName': 'MainProcess', 'args': ((u'NotFound', u'7654'),), 'module': 'app', 'filename': 'app.py', 'levelno': 40, 'exc_text': None, 'pathname': '/root/bipapa/app.py', 'lineno': 118, 'msg': 'genreid %s is %s', 'exc_info': None, 'funcName': 'get', 'relativeCreated': 1082.8020572662354, 'levelname': 'ERROR', 'msecs': 334.7010612487793}", 'funcName': 'get', 'relativeCreated': 1082.8020572662354, 'levelname': 'ERROR', 'msecs': 334.7010612487793}
[W 120725 15:04:10 web:1447] 404 GET /genreid/7654 (192.168.32.17) 30.01ms
[W 120725 15:04:10 web:1447] 404 GET /favicon.ico (192.168.32.17) 1.09ms
[E 120725 15:04:16 app:118] Bad message (TypeError('not enough arguments for format string',)): {'threadName': 'MainThread', 'name': 'root', 'thread': 140293953246976, 'created': 1343196256.743716, 'process': 30922, 'processName': 'MainProcess', 'args': ((u'NotFound', u'7654'),), 'module': 'app', 'filename': 'app.py', 'levelno': 40, 'exc_text': None, 'pathname': '/root/bipapa/app.py', 'lineno': 118, 'asctime': '120725 15:04:16', 'msg': 'genreid %s is %s', 'exc_info': None, 'message': "Bad message (TypeError('not enough arguments for format string',)): {'threadName': 'MainThread', 'name': 'root', 'thread': 140293953246976, 'created': 1343196256.743716, 'process': 30922, 'processName': 'MainProcess', 'args': ((u'NotFound', u'7654'),), 'module': 'app', 'filename': 'app.py', 'levelno': 40, 'exc_text': None, 'pathname': '/root/bipapa/app.py', 'lineno': 118, 'msg': 'genreid %s is %s', 'exc_info': None, 'funcName': 'get', 'relativeCreated': 7491.8169975280762, 'levelname': 'ERROR', 'msecs': 743.71600151062012}", 'funcName': 'get', 'relativeCreated': 7491.8169975280762, 'levelname': 'ERROR', 'msecs': 743.71600151062012}
[W 120725 15:04:16 web:1447] 404 GET /genreid/7654 (192.168.32.17) 18.67ms
[W 120725 15:04:17 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[I 120725 15:05:17 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120725 15:05:39 web:1447] 304 GET /genreid/ (192.168.32.17) 35.76ms
[W 120725 15:05:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.88ms
[I 120725 17:07:25 web:1447] 200 GET /genreid/ (192.168.32.17) 71.30ms
[W 120725 17:07:44 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.89ms
[I 120725 17:43:14 web:1447] 304 GET /genreid/ (192.168.32.17) 38.80ms
[W 120725 17:43:15 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.86ms
[W 120725 17:43:18 web:1447] 405 POST /genreid/ (192.168.32.17) 0.37ms
[W 120725 17:43:18 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120725 17:43:19 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120725 17:43:21 web:1447] 405 POST /genreid/ (192.168.32.17) 0.34ms
[W 120725 17:43:22 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.60ms
[W 120725 17:43:24 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120725 17:43:30 web:1447] 200 GET /genreid/101240 (192.168.32.17) 28.56ms
[W 120725 17:43:31 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.81ms
[I 120725 17:43:33 web:1447] 200 GET /genreid/101354 (192.168.32.17) 26.86ms
[W 120725 17:43:33 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.81ms
[I 120725 17:43:34 web:1447] 200 GET /genreid/101355 (192.168.32.17) 26.81ms
[W 120725 17:43:35 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120725 17:43:35 web:1447] 200 GET /genreid/101361 (192.168.32.17) 21.33ms
[W 120725 17:43:36 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.81ms
[W 120725 17:43:37 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120725 17:43:37 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120725 17:43:37 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120725 17:43:38 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[W 120725 17:43:40 web:1447] 405 POST /genreid/ (192.168.32.17) 0.36ms
[W 120725 17:43:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[W 120725 17:43:42 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[W 120725 17:43:46 web:1447] 405 POST /genreid/ (192.168.32.17) 0.34ms
[W 120725 17:43:47 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120725 17:49:51 web:1447] 304 GET /genreid/ (192.168.32.17) 42.96ms
[W 120725 17:49:52 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[W 120726 08:57:22 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.52ms
[I 120726 09:47:00 web:1447] 200 GET / (192.168.32.17) 1.01ms
[I 120726 11:28:35 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120726 11:28:41 web:1447] 304 GET / (192.168.32.17) 3.67ms
[E 120726 11:28:45 web:1064] Uncaught exception GET /genreid/ (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'If-None-Match': '"8df96c800eae95db4781ff72d7f77e266dbac563"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 122, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 69, in rakuten_api
        c. perfor()
    AttributeError: perfor
[E 120726 11:28:45 web:1447] 500 GET /genreid/ (192.168.32.17) 1.42ms
[W 120726 11:28:51 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.39ms
[I 120726 11:28:57 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120726 11:29:02 web:1064] Uncaught exception GET /genreid/ (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 122, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 71, in rakuten_api
        api_result = tornado.escape.json_decode(response.read())
    AttributeError: 'str' object has no attribute 'read'
[E 120726 11:29:02 web:1447] 500 GET /genreid/ (192.168.32.17) 23.69ms
[W 120726 11:29:02 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.38ms
[I 120726 11:32:57 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120726 11:32:59 web:1447] 200 GET /genreid/ (192.168.32.17) 35.03ms
[W 120726 11:33:00 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.91ms
[E 120726 11:33:01 web:1064] Uncaught exception GET /genreid/215783 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/215783', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Referer': 'http://10.24.94.36:8888/genreid/'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 123, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 65, in rakuten_api
        c.setopt(pycurl.URL, url)
    TypeError: invalid arguments to setopt
[E 120726 11:33:01 web:1447] 500 GET /genreid/215783 (192.168.32.17) 0.72ms
[W 120726 11:33:02 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[W 120726 11:33:08 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.39ms
[E 120726 11:33:19 web:1064] Uncaught exception GET /genreid/101381 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/101381', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Referer': 'http://10.24.94.36:8888/genreid/'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 123, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 65, in rakuten_api
        c.setopt(pycurl.URL, url)
    TypeError: invalid arguments to setopt
[E 120726 11:33:19 web:1447] 500 GET /genreid/101381 (192.168.32.17) 0.81ms
[W 120726 11:33:19 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120726 11:34:10 web:1064] Uncaught exception GET /genreid/101381 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/101381', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 123, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 65, in rakuten_api
        c.setopt(pycurl.URL, url)
    TypeError: invalid arguments to setopt
[E 120726 11:34:10 web:1447] 500 GET /genreid/101381 (192.168.32.17) 0.63ms
[W 120726 11:34:11 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[W 120726 11:34:14 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120726 11:34:15 web:1064] Uncaught exception GET /genreid/101240 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/101240', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Referer': 'http://10.24.94.36:8888/genreid/', 'If-None-Match': '"c0a499b3cd3a1524613afd875f937c188ba9472e"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 123, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 65, in rakuten_api
        c.setopt(pycurl.URL, url)
    TypeError: invalid arguments to setopt
[E 120726 11:34:15 web:1447] 500 GET /genreid/101240 (192.168.32.17) 0.61ms
[W 120726 11:34:15 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120726 11:34:44 autoreload:175] /root/bipapa/app.py modified; restarting server
[W 120726 11:34:46 web:1447] 404 GET /genreid (192.168.32.17) 1.16ms
[W 120726 11:34:47 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.40ms
[I 120726 11:34:50 web:1447] 200 GET /genreid/ (192.168.32.17) 27.24ms
[W 120726 11:34:51 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120726 11:34:52 web:1447] 304 GET /genreid/ (192.168.32.17) 26.39ms
[W 120726 11:34:53 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120726 11:34:53 web:1447] 304 GET /genreid/ (192.168.32.17) 29.57ms
[W 120726 11:34:53 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[E 120726 11:34:53 web:1064] Uncaught exception GET /genreid/ (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'If-None-Match': '"c0a499b3cd3a1524613afd875f937c188ba9472e"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 126, in get
        self.render("genreid.html", message = grenreid_doc)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 580, in render
        self.finish(html)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 701, in finish
        self.request.finish()
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 433, in finish
        self.connection.finish()
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 187, in finish
        self._finish_request()
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 223, in _finish_request
        self.stream.read_until(b("\r\n\r\n"), self._header_callback)
      File "/usr/lib/python2.6/site-packages/tornado/iostream.py", line 153, in read_until
        self._try_inline_read()
      File "/usr/lib/python2.6/site-packages/tornado/iostream.py", line 381, in _try_inline_read
        self._check_closed()
      File "/usr/lib/python2.6/site-packages/tornado/iostream.py", line 564, in _check_closed
        raise IOError("Stream is closed")
    IOError: Stream is closed
[E 120726 11:34:53 web:718] Cannot send error response after headers written
[E 120726 11:34:53 iostream:307] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/iostream.py", line 304, in wrapper
        callback(*args)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 262, in _on_headers
        self.request_callback(self._request)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1412, in __call__
        handler._execute(transforms, *args, **kwargs)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1025, in _execute
        self._handle_request_exception(e)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1065, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 720, in send_error
        self.finish()
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 700, in finish
        self.flush(include_footers=True)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 660, in flush
        self.request.write(headers + chunk, callback=callback)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 429, in write
        self.connection.write(chunk, callback=callback)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 177, in write
        assert self._request, "Request closed"
    AssertionError: Request closed
[E 120726 11:34:53 ioloop:435] Exception in callback <tornado.stack_context._StackContextWrapper object at 0x218e7e0>
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/ioloop.py", line 421, in _run_callback
        callback()
      File "/usr/lib/python2.6/site-packages/tornado/iostream.py", line 304, in wrapper
        callback(*args)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 262, in _on_headers
        self.request_callback(self._request)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1412, in __call__
        handler._execute(transforms, *args, **kwargs)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1025, in _execute
        self._handle_request_exception(e)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1065, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 720, in send_error
        self.finish()
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 700, in finish
        self.flush(include_footers=True)
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 660, in flush
        self.request.write(headers + chunk, callback=callback)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 429, in write
        self.connection.write(chunk, callback=callback)
      File "/usr/lib/python2.6/site-packages/tornado/httpserver.py", line 177, in write
        assert self._request, "Request closed"
    AssertionError: Request closed
[I 120726 11:34:53 web:1447] 200 GET /genreid/ (192.168.32.17) 24.75ms
[W 120726 11:34:54 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120726 11:34:58 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120726 11:34:59 web:1447] 200 GET /genreid/ (192.168.32.17) 35.29ms
[W 120726 11:35:00 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.90ms
[E 120726 11:35:00 web:1064] Uncaught exception GET /genreid/100533 (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/genreid/100533', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Referer': 'http://10.24.94.36:8888/genreid/'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 123, in get
        genreId = genreId)
      File "/root/bipapa/app.py", line 65, in rakuten_api
        c.setopt(pycurl.URL, url)
    TypeError: invalid arguments to setopt
[E 120726 11:35:00 web:1447] 500 GET /genreid/100533 (192.168.32.17) 0.73ms
[W 120726 11:35:01 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120726 11:36:06 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120726 11:36:07 web:1447] 200 GET /genreid/100533 (192.168.32.17) 31.45ms
[W 120726 11:36:07 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.87ms
[I 120726 11:36:11 web:1447] 304 GET /genreid/ (192.168.32.17) 28.93ms
[W 120726 11:36:11 web:1447] 404 GET /genreid (192.168.32.17) 0.75ms
[W 120726 11:36:11 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120726 11:36:12 web:1447] 304 GET /genreid/ (192.168.32.17) 24.98ms
[W 120726 11:36:13 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120726 11:36:14 web:1447] 200 GET /genreid/100938 (192.168.32.17) 26.38ms
[W 120726 11:36:14 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.82ms
[I 120726 11:37:42 web:1447] 304 GET /genreid/ (192.168.32.17) 24.84ms
[W 120726 11:37:42 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.83ms
[I 120727 09:33:39 web:1447] 304 GET /genreid/ (192.168.32.17) 128.51ms
[W 120727 09:33:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.89ms
[I 120727 09:33:40 web:1447] 304 GET /genreid/ (192.168.32.17) 27.04ms
[W 120727 09:33:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.84ms
[I 120727 09:33:40 web:1447] 304 GET /genreid/ (192.168.32.17) 36.35ms
[I 120727 09:33:40 web:1447] 200 GET /genreid/ (192.168.32.17) 34.39ms
[W 120727 09:33:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.83ms
[I 120730 11:42:26 web:1447] 304 GET / (192.168.32.17) 15.02ms
[I 120801 15:19:07 web:1447] 304 GET / (192.168.32.17) 16.95ms
[W 120801 15:19:08 web:1447] 404 GET /favicon.ico (192.168.32.17) 12.49ms
[I 120801 15:19:10 web:1447] 200 GET /genreid/ (192.168.32.17) 84.62ms
[W 120801 15:19:11 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.88ms
[I 120801 15:19:16 web:1447] 200 GET /genreid/100371 (192.168.32.17) 31.34ms
[W 120801 15:19:17 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.81ms
[I 120801 15:20:31 web:1447] 200 GET /genreid/110729 (192.168.32.17) 49.33ms
[W 120801 15:20:32 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.83ms
[I 120801 18:08:57 web:1447] 304 GET / (192.168.32.17) 8.16ms
[I 120802 18:46:05 web:1447] 304 GET / (192.168.32.17) 12.78ms
[W 120802 18:46:06 web:1447] 404 GET /favicon.ico (192.168.32.17) 21.76ms
[I 120802 19:16:02 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:17:26 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:17:55 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:18:50 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:19:34 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:20:18 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:20:22 web:1447] 200 GET / (192.168.32.17) 0.56ms
[W 120802 19:20:23 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.99ms
[I 120802 19:20:46 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:20:47 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'If-None-Match': '"d1a112a8e0f2117e090bfdddc8780304897e7817"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.write(getimg())
      File "/root/bipapa/app.py", line 140, in getimg
        conn.close()
    NameError: global name 'conn' is not defined
[E 120802 19:20:47 web:1447] 500 GET / (192.168.32.17) 8.26ms
[W 120802 19:20:48 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.50ms
[I 120802 19:21:02 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:21:04 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.write(getimg())
      File "/root/bipapa/app.py", line 140, in getimg
        db.close()
      File "/usr/lib64/python2.6/site-packages/pymongo/collection.py", line 1193, in __call__
        self.__name)
    TypeError: 'Collection' object is not callable. If you meant to call the 'close' method on a 'Database' object it is failing because no such method exists.
[E 120802 19:21:04 web:1447] 500 GET / (192.168.32.17) 17.57ms
[W 120802 19:21:04 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.51ms
[E 120802 19:21:05 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.write(getimg())
      File "/root/bipapa/app.py", line 140, in getimg
        db.close()
      File "/usr/lib64/python2.6/site-packages/pymongo/collection.py", line 1193, in __call__
        self.__name)
    TypeError: 'Collection' object is not callable. If you meant to call the 'close' method on a 'Database' object it is failing because no such method exists.
[E 120802 19:21:05 web:1447] 500 GET / (192.168.32.17) 4.42ms
[W 120802 19:21:05 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[E 120802 19:21:05 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.write(getimg())
      File "/root/bipapa/app.py", line 140, in getimg
        db.close()
      File "/usr/lib64/python2.6/site-packages/pymongo/collection.py", line 1193, in __call__
        self.__name)
    TypeError: 'Collection' object is not callable. If you meant to call the 'close' method on a 'Database' object it is failing because no such method exists.
[E 120802 19:21:05 web:1447] 500 GET / (192.168.32.17) 4.35ms
[W 120802 19:21:06 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[I 120802 19:21:09 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:21:10 web:1447] 200 GET / (192.168.32.17) 6.40ms
[W 120802 19:21:13 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.92ms
[I 120802 19:21:35 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:21:38 web:1447] 200 GET / (192.168.32.17) 4.95ms
[W 120802 19:21:39 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.94ms
[I 120802 19:21:39 web:1447] 304 GET / (192.168.32.17) 3.52ms
[W 120802 19:21:40 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.34ms
[I 120802 19:23:02 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:23:08 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'If-None-Match': '"39302de821b2e98e5347bac175d40828aa85b78b"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 144, in get
        self.write(getimg(), mimetype="image/JPEG")
    TypeError: write() got an unexpected keyword argument 'mimetype'
[E 120802 19:23:08 web:1447] 500 GET / (192.168.32.17) 6.96ms
[W 120802 19:23:09 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.51ms
[I 120802 19:25:18 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:25:20 web:1447] 200 GET / (192.168.32.17) 6.33ms
[W 120802 19:25:21 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.92ms
[I 120802 19:26:15 web:1447] 304 GET / (192.168.32.17) 4.75ms
[W 120802 19:26:17 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120802 19:26:18 web:1447] 304 GET / (192.168.32.17) 4.33ms
[W 120802 19:26:18 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[I 120802 19:26:19 web:1447] 304 GET / (192.168.32.17) 4.19ms
[I 120802 19:26:21 web:1447] 304 GET / (192.168.32.17) 4.31ms
[W 120802 19:26:22 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[I 120802 19:26:31 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:26:34 web:1447] 200 GET / (192.168.32.17) 3.61ms
[W 120802 19:26:35 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.96ms
[I 120802 19:37:59 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:38:18 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:38:33 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:38:37 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'If-None-Match': '"3a943bf02172361d014e4334497e5af16f24bff3"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 144, in get
        self.set_header("Content-Type", im.content_type)
    NameError: global name 'im' is not defined
[E 120802 19:38:37 web:1447] 500 GET / (192.168.32.17) 1.47ms
[W 120802 19:38:38 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.38ms
[I 120802 19:38:55 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:38:56 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.set_header("Content-Type", im.content_type)
    AttributeError: 'str' object has no attribute 'content_type'
[E 120802 19:38:56 web:1447] 500 GET / (192.168.32.17) 5.56ms
[W 120802 19:38:57 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.36ms
[E 120802 19:38:57 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.set_header("Content-Type", im.content_type)
    AttributeError: 'str' object has no attribute 'content_type'
[E 120802 19:38:57 web:1447] 500 GET / (192.168.32.17) 3.77ms
[W 120802 19:38:57 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120802 19:38:57 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.set_header("Content-Type", im.content_type)
    AttributeError: 'str' object has no attribute 'content_type'
[E 120802 19:38:57 web:1447] 500 GET / (192.168.32.17) 3.33ms
[W 120802 19:38:58 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[E 120802 19:38:58 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        self.set_header("Content-Type", im.content_type)
    AttributeError: 'str' object has no attribute 'content_type'
[E 120802 19:38:58 web:1447] 500 GET / (192.168.32.17) 3.36ms
[W 120802 19:38:58 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.35ms
[I 120802 19:42:08 autoreload:175] /root/bipapa/app.py modified; restarting server
[E 120802 19:42:10 web:1064] Uncaught exception GET / (192.168.32.17)
    HTTPRequest(protocol='http', host='10.24.94.36:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.32.17', body='', headers={'Accept-Language': 'ja,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4,zh;q=0.2,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '10.24.94.36:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11', 'Accept-Charset': 'UTF-8,*;q=0.5', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1021, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/bipapa/app.py", line 145, in get
        (im,dic) = getimg()
      File "/root/bipapa/app.py", line 140, in getimg
        dic = im.content_type
    AttributeError: 'str' object has no attribute 'content_type'
[E 120802 19:42:10 web:1447] 500 GET / (192.168.32.17) 6.40ms
[W 120802 19:42:10 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.38ms
[I 120802 19:43:30 autoreload:175] /root/bipapa/app.py modified; restarting server
[I 120802 19:43:32 web:1447] 200 GET / (192.168.32.17) 6.22ms
[W 120802 19:43:33 web:1447] 404 GET /favicon.ico (192.168.32.17) 0.94ms
